AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - config/**/*

ClassAndModuleChildren:
  Enabled: false

ClassLength:
  CountComments: false
  Max: 100

Documentation:
  Enabled: false

LineLength:
  Enabled: true
  Max: 79

MethodLength:
  CountComments: false
  Max: 5

ParameterLists:
  Max: 4
  CountKeywordArgs: true

TrailingWhitespace:
  Enabled: true

Style/BlockComments:
  Enabled: false

Style/FileName:
  Enabled: false
